# Generated by Django 4.2.7 on 2024-02-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouee', '0002_donneescapteures_donneesgnss_delete_donnees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneescapteures',
            name='hum',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donneescapteures',
            name='press',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donneescapteures',
            name='temp',
            field=models.FloatField(max_length=10),
        ),
    ]
