# Generated by Django 4.2.7 on 2024-02-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouee', '0003_alter_donneescapteures_hum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneesgnss',
            name='nombredesattelite',
            field=models.CharField(max_length=10),
        ),
    ]
